name = "spinogambino-test-fr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-test.fr"
HMAC_KEY = "2cf97eecd6ffea15f057f9051c3c150d8718c543a190655e4d47dbdd64a1d1ed"
COOKIE_NAME = "mkv"
PLAY_PATH = "start"
BUTTON_ID = "p80ae639341fbb045c69247ceb6fe9625"
GATE_SALT = "3b95cfeda136fc6b"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "m8u1"
CTA_SELECTOR = ".play-button"
